package main

// retrieval-bench is the #730 Round-B measurement harness: it drives the
// production HybridRetriever directly (same composition root as rag-probe)
// with rerank ON vs OFF, against the real local database while the embedding
// and rerank providers are replaced by an embedded deterministic mock server.
//
// Why a Go harness and not k6: the rerank switch only exists on the agent
// retrieval path (anonymous /contents/search never reranks — verified link
// fact), and driving it through authenticated HTTP agent rounds would mix in
// LLM generation latency and agent quotas. Direct drive isolates retrieval.
//
// Mock contract (this binary serves both):
//   POST /v1/embeddings                                  (OpenAI shape)
//   POST /api/v1/services/rerank/text-rerank/text-rerank (DashScope shape)
// Vectors are 1536-dim deterministic (sha256-seeded per text), matching the
// chunk_embeddings column; semantic ordering under the mock is therefore
// synthetic and the report must say so — keyword half, RRF fusion and rerank
// call counts remain fully real.
//
// Fail-fast assertions BEFORE sampling (spec: pre-run, not post-hoc):
// effective config matches the -rerank intent (override actually loaded),
// expansion off, hybrid on, embedder reachable with 1536 dims, and a
// multi-candidate probe where the ON run must actually call the reranker
// (guards the factory's silent-nil degradation) while the OFF run must make
// zero rerank calls.

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"os"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"omnicraft/backend/config"
	"omnicraft/backend/internal/container"
	"omnicraft/backend/internal/pkg/database"
	redisclient "omnicraft/backend/internal/pkg/redis"
)

const mockDims = 1536

type mockCounters struct {
	embeddings atomic.Int64
	rerank     atomic.Int64
}

func deterministicVector(text string) []float64 {
	sum := sha256.Sum256([]byte("embed:" + text))
	vec := make([]float64, mockDims)
	for i := range vec {
		sum = sha256.Sum256(sum[:])
		vec[i] = float64(sum[0])/255.0*2 - 1
	}
	return vec
}

func startMock(addrCh chan<- string, counters *mockCounters) *http.Server {
	server := &http.Server{}
	mux := http.NewServeMux()

	mux.HandleFunc("/v1/embeddings", func(w http.ResponseWriter, r *http.Request) {
		counters.embeddings.Add(1)
		var req struct {
			Input []string `json:"input"`
		}
		body, _ := io.ReadAll(r.Body)
		if err := json.Unmarshal(body, &req); err != nil || len(req.Input) == 0 {
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		data := make([]map[string]any, 0, len(req.Input))
		for _, text := range req.Input {
			data = append(data, map[string]any{"embedding": deterministicVector(text)})
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": data})
	})

	mux.HandleFunc("/api/v1/services/rerank/text-rerank/text-rerank", func(w http.ResponseWriter, r *http.Request) {
		counters.rerank.Add(1)
		var req struct {
			Input struct {
				Query     string   `json:"query"`
				Documents []string `json:"documents"`
			} `json:"input"`
		}
		body, _ := io.ReadAll(r.Body)
		if err := json.Unmarshal(body, &req); err != nil {
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		type result struct {
			Index          int     `json:"index"`
			RelevanceScore float64 `json:"relevance_score"`
		}
		results := make([]result, 0, len(req.Input.Documents))
		for i, doc := range req.Input.Documents {
			sum := sha256.Sum256([]byte(req.Input.Query + "\x00" + doc))
			results = append(results, result{Index: i, RelevanceScore: float64(sum[0]) / 255.0})
		}
		sort.Slice(results, func(a, b int) bool { return results[a].RelevanceScore > results[b].RelevanceScore })
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"output": map[string]any{"results": results}})
	})

	server.Handler = mux
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		slog.Error("mock listen", "error", err)
		os.Exit(1)
	}
	addrCh <- listener.Addr().String()
	go func() { _ = server.Serve(listener) }()
	return server
}

func writeOverride(path, mockBase string, rerankOn bool) error {
	rerankFlag := "false"
	if rerankOn {
		rerankFlag = "true"
	}
	content := fmt.Sprintf(`# generated by retrieval-bench (#730 round B) — mock providers only
features:
  rag_hybrid_enabled: true
  rag_query_expansion_enabled: false
  rag_rerank_enabled: %s
agent:
  embedding_provider: "openai_compat"
  embedding_model: "mock-embedding"
  embedding_api_base: "%s"
  embedding_api_key: "mock-key"
  embedding_dimensions: %d
rag:
  index:
    embedding_model: "mock-embedding"
  rerank:
    provider: "dashscope"
    model: "mock-rerank"
    api_base: "%s"
    api_key: "mock-key"
    fallback_provider: ""
    fallback_model: ""
    fallback_api_key: ""
    fallback_api_key_placeholder_skip: ""
`, rerankFlag, mockBase, mockDims, mockBase)
	return os.WriteFile(path, []byte(content), 0o600)
}

// writeRealOverride flips only the rerank switch: providers come from the
// ambient environment (real keys, never committed) — the budget-gated
// small-sample round. Rerank invocation proof in real mode relies on the
// absence of rerank_unavailable degradation (a nil reranker under an enabled
// switch would surface there), not on call counters.
func writeRealOverride(path string, rerankOn bool) error {
	rerankFlag := "false"
	if rerankOn {
		rerankFlag = "true"
	}
	content := fmt.Sprintf(`# generated by retrieval-bench (#730 round B, real-provider small sample)
features:
  rag_hybrid_enabled: true
  rag_query_expansion_enabled: false
  rag_rerank_enabled: %s
`, rerankFlag)
	return os.WriteFile(path, []byte(content), 0o600)
}

type benchInput struct {
	Queries []string `json:"queries"`
	Viewer  int64    `json:"viewer_id"`
}

type outcomeCounts struct {
	Hit      int `json:"hit"`
	Empty    int `json:"empty"`
	Error    int `json:"error"`
	Degraded int `json:"degraded"`
	// DegradedByKind splits Degraded by the retriever's reason constant so
	// mock artifacts (e.g. synthetic vectors below the semantic threshold
	// forcing keyword_fallback) stay distinguishable from real degradation.
	DegradedByKind map[string]int `json:"degraded_by_kind"`
}

type summary struct {
	Engine          string         `json:"engine"`
	RerankFlag      bool           `json:"rerank_on"`
	EffectiveConfig map[string]any `json:"effective_config"`
	Queries         int            `json:"queries"`
	Concurrency     int            `json:"concurrency"`
	LatencyMs       map[string]any `json:"latency_ms"`
	Outcomes        outcomeCounts  `json:"outcomes"`
	RerankCalls     any            `json:"rerank_calls"`
	EmbeddingCalls  any            `json:"embedding_calls"`
	Probe           map[string]any `json:"probe"`
	Notes           []string       `json:"notes"`
}

func percentile(sorted []float64, p float64) float64 {
	if len(sorted) == 0 {
		return 0
	}
	idx := int(float64(len(sorted)-1) * p)
	if idx < 0 {
		idx = 0
	}
	return sorted[idx]
}

func main() {
	rerankFlag := flag.String("rerank", "", "on|off (required)")
	useMock := flag.Bool("mock", true, "embedded deterministic mock providers (false = real providers from env/config, budget-gated small-sample round)")
	in := flag.String("in", "", "input json {queries:[...], viewer_id}")
	out := flag.String("out", "", "output summary json path")
	concurrency := flag.Int("concurrency", 4, "bounded parallel retrieves")
	perReqTimeout := flag.Duration("timeout", 5*time.Second, "per-retrieve timeout")
	flag.Parse()
	if *rerankFlag != "on" && *rerankFlag != "off" || *in == "" || *out == "" {
		slog.Error("usage: retrieval-bench -rerank on|off -in queries.json -out result.json [-concurrency 4]")
		os.Exit(2)
	}
	rerankOn := *rerankFlag == "on"

	counters := &mockCounters{}
	var mockServer *http.Server
	mockBase := ""
	overridePath := fmt.Sprintf("/tmp/retrieval-bench-override-%s.yaml", *rerankFlag)
	if *useMock {
		addrCh := make(chan string, 1)
		mockServer = startMock(addrCh, counters)
		defer func() { _ = mockServer.Close() }()
		mockBase = "http://" + <-addrCh
		if err := writeOverride(overridePath, mockBase, rerankOn); err != nil {
			slog.Error("write override", "error", err)
			os.Exit(1)
		}
	} else if err := writeRealOverride(overridePath, rerankOn); err != nil {
		slog.Error("write override", "error", err)
		os.Exit(1)
	}
	defer func() { _ = os.Remove(overridePath) }()
	_ = os.Setenv("CONFIG_OVERRIDE_PATH", overridePath)

	cfg := config.Load()

	// --- pre-run assertions (fail fast, before any sampling) ---
	if !cfg.Features.RAGHybridEnabled {
		slog.Error("effective config: rag_hybrid_enabled must be true (override not loaded?)")
		os.Exit(3)
	}
	if cfg.Features.RAGQueryExpansionEnabled {
		slog.Error("effective config: rag_query_expansion_enabled must be false")
		os.Exit(3)
	}
	if cfg.Features.RAGRerankEnabled != rerankOn {
		slog.Error("effective config: rag_rerank_enabled mismatch", "want", rerankOn, "got", cfg.Features.RAGRerankEnabled)
		os.Exit(3)
	}
	slog.Info("effective config asserted", "hybrid", true, "expansion", false, "rerank", rerankOn)

	db := database.Init(cfg)
	rdb := redisclient.Init(cfg)
	defer rdb.Close()
	ctr, err := container.NewContainer(db, rdb, cfg)
	if err != nil {
		slog.Error("composition root wiring incomplete", "error", err)
		os.Exit(1)
	}

	var input benchInput
	raw, err := os.ReadFile(*in)
	if err != nil {
		slog.Error("read input", "error", err)
		os.Exit(1)
	}
	if err := json.Unmarshal(raw, &input); err != nil {
		slog.Error("parse input", "error", err)
		os.Exit(1)
	}

	// Multi-candidate probe: prove the ON run actually reaches the reranker
	// and the OFF run makes zero rerank calls (factory silent-nil guard).
	// The probe uses a guaranteed-broad corpus IP term (wiring check only,
	// never part of the measured set).
	probeCtx, probeCancel := context.WithTimeout(context.Background(), *perReqTimeout)
	res, err := ctr.HybridRetriever.Retrieve(probeCtx, "原神", input.Viewer)
	probeCancel()
	probeInfo := map[string]any{"candidates": 0, "error": ""}
	if err != nil {
		probeInfo["error"] = err.Error()
		slog.Error("probe retrieve failed", "error", err)
		os.Exit(3)
	}
	probeInfo["candidates"] = len(res.Candidates)
	if len(res.Candidates) < 2 {
		slog.Error("probe must return multiple candidates to exercise rerank", "got", len(res.Candidates))
		os.Exit(3)
	}
	probeRerank := counters.rerank.Load()
	probeInfo["rerank_calls"] = probeRerank
	if *useMock {
		if rerankOn && probeRerank == 0 {
			slog.Error("rerank ON but probe made zero rerank calls (reranker silently nil?) — aborting")
			os.Exit(3)
		}
		if !rerankOn && probeRerank != 0 {
			slog.Error("rerank OFF but probe made rerank calls — aborting", "calls", probeRerank)
			os.Exit(3)
		}
	} else if rerankOn && res.Degraded == "rerank_unavailable" {
		slog.Error("real mode: rerank ON but retriever reports rerank_unavailable (nil reranker?) — aborting")
		os.Exit(3)
	}
	slog.Info("probe ok", "candidates", len(res.Candidates), "rerank_calls", probeRerank)

	// --- measured run ---
	var mu sync.Mutex
	latencies := make([]float64, 0, len(input.Queries))
	outcomes := outcomeCounts{DegradedByKind: map[string]int{}}
	sem := make(chan struct{}, *concurrency)
	var wg sync.WaitGroup
	for _, q := range input.Queries {
		wg.Add(1)
		go func(query string) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			ctx, cancel := context.WithTimeout(context.Background(), *perReqTimeout)
			started := time.Now()
			res, err := ctr.HybridRetriever.Retrieve(ctx, query, input.Viewer)
			took := time.Since(started).Milliseconds()
			cancel()
			mu.Lock()
			defer mu.Unlock()
			latencies = append(latencies, float64(took))
			switch {
			case err != nil:
				outcomes.Error++
			case len(res.Candidates) == 0:
				outcomes.Empty++
			default:
				outcomes.Hit++
			}
			if err == nil && res.Degraded != "" {
				outcomes.Degraded++
				outcomes.DegradedByKind[res.Degraded]++
			}
		}(q)
	}
	wg.Wait()

	sort.Float64s(latencies)
	var rerankCalls, embedCalls any = counters.rerank.Load(), counters.embeddings.Load()
	notes := []string{
		"real local DB retrieval; embedding+rerank are deterministic local mocks (zero provider cost)",
		"mock vectors are text-hash deterministic — semantic ordering is synthetic, keyword half + RRF fusion are real",
		"rerank latency contribution under mock ≈ transport only; real-API calibration is a separate small-sample round",
	}
	if !*useMock {
		rerankCalls, embedCalls = nil, nil
		notes = []string{
			"REAL provider small-sample round (budget-gated, ≤24 queries, single concurrency): latency contribution calibration only",
			"rerank invocation proof = no rerank_unavailable degradation on the ON run; no call counters available off-process",
			"not a steady-state P95/P99 or capacity claim",
		}
	}
	sum := summary{
		Engine:     "go-harness (direct HybridRetriever, mock embedding+rerank)",
		RerankFlag: rerankOn,
		EffectiveConfig: map[string]any{
			"rag_hybrid_enabled":          cfg.Features.RAGHybridEnabled,
			"rag_query_expansion_enabled": cfg.Features.RAGQueryExpansionEnabled,
			"rag_rerank_enabled":          cfg.Features.RAGRerankEnabled,
			"override_path":               overridePath,
		},
		Queries:     len(input.Queries),
		Concurrency: *concurrency,
		LatencyMs: map[string]any{
			"p50": percentile(latencies, 0.50), "p95": percentile(latencies, 0.95),
			"p99": percentile(latencies, 0.99), "max": percentile(latencies, 1.0),
		},
		Outcomes:       outcomes,
		RerankCalls:    rerankCalls,
		EmbeddingCalls: embedCalls,
		Probe:          probeInfo,
		Notes:          notes,
	}
	encoded, _ := json.MarshalIndent(sum, "", "  ")
	if err := os.WriteFile(*out, encoded, 0o644); err != nil {
		slog.Error("write summary", "error", err)
		os.Exit(1)
	}
	fmt.Println(string(encoded))
}
