#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Media asset sourcing, synthesis and validation for demo_showcase_seed (#848).

All parsing/synthesis here is stdlib-only (Python 3.9+) and fully offline:

- Source reuse: the 16 real JPGs under frontend/public/seed-media/real/covers
  (NOTE: seed-media/real/gallery holds SVG placeholders, covers/ holds the
  real JPGs) and the two real MP4s under .../videos/fitness-{1,2}.mp4.
  fitness-3.mp4 is a mislabelled JPEG (ffd8 magic, 3456x4608) and is
  deliberately NOT used as a video source.
- Synthesis: WAV audio (pure-Python PCM; ffmpeg MP3 path used only when an
  ffmpeg binary is detected), MIDI sheet music, binary STL, mod zip, OPC
  docx, csv, plain-text notes.

Generated bytes are written into the caller-provided work directory (never
into tracked repo paths) and validated on every dry-run:

  kind      assertion
  --------  -----------------------------------------------------------
  image     JPEG SOF parse yields positive width/height; ffd8 magic
  video     MP4 box walk yields mvhd duration <=180s and tkhd 16.16 w/h
  audio     header magic matches the claimed extension (mirrors the backend
            upload_families.go audioMagicSignatures table)
  mod       zipfile.testzip() clean; PK magic; application/zip payload
  stl       84 + 50*triangle_count == file size; tetra normals normalized
  mid       MThd header + exactly one MTrk + running end-of-track
  docx      OPC identity parts ([Content_Types].xml + word/document.xml),
            no vbaProject.bin (mirrors document_validation.go checks)
  csv       no NUL bytes, printable ratio >= 0.9 (mirrors CSV sanity gate)
  text      non-empty UTF-8
"""
from __future__ import annotations

import math
import os
import shutil
import struct
import subprocess
import zipfile
from typing import Any, Dict, List, Optional, Tuple

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SEED_MEDIA_REAL = os.path.join(REPO_ROOT, "frontend", "public", "seed-media", "real")
COVERS_DIR = os.path.join(SEED_MEDIA_REAL, "covers")
VIDEOS_DIR = os.path.join(SEED_MEDIA_REAL, "videos")

# Real MP4 sources only. fitness-3.mp4 is a JPEG with a .mp4 name -- it can
# never satisfy the video/* presign + mvhd parsing contract.
VIDEO_SOURCES = ["fitness-1.mp4", "fitness-2.mp4"]

# Mirrors backend upload_families.go audioMagicSignatures (prefix check).
AUDIO_MAGIC_BY_EXT: Dict[str, List[bytes]] = {
    ".mp3": [b"ID3", b"\xff\xfb", b"\xff\xf3", b"\xff\xf2", b"\xff\xf7", b"\xff\xf1"],
    ".wav": [b"RIFF"],
    ".flac": [b"fLaC"],
    ".ogg": [b"OggS"],
    ".opus": [b"OggS"],
    ".m4a": [b"\x00\x00\x00"],
    ".aac": [b"\xff\xf1", b"\xff\xf9", b"OggS"],
}


def detect_ffmpeg() -> Optional[str]:
    return shutil.which("ffmpeg")


# ------------------------------------------------------------ media parsing

def jpeg_dimensions(path: str) -> Tuple[int, int]:
    """Parse width/height from the first SOF marker (no external deps)."""
    with open(path, "rb") as fh:
        data = fh.read(1 << 20)
    if data[:2] != b"\xff\xd8":
        raise ValueError("not a JPEG: missing SOI marker")
    i = 2
    size = len(data)
    while i + 4 < size:
        if data[i] != 0xFF:
            i += 1
            continue
        marker = data[i + 1]
        if marker == 0xFF:
            i += 1
            continue
        if marker == 0xD8 or marker == 0x01 or 0xD0 <= marker <= 0xD7:
            i += 2
            continue
        if i + 4 > size:
            break
        seg_len = struct.unpack(">H", data[i + 2:i + 4])[0]
        if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
            height, width = struct.unpack(">HH", data[i + 5:i + 9])
            if width > 0 and height > 0:
                return width, height
            raise ValueError("SOF marker with non-positive dimensions")
        i += 2 + seg_len
    raise ValueError("no SOF marker found (unsupported JPEG)")


def _mp4_boxes(data: bytes, start: int, end: int) -> List[Tuple[str, int, int, int]]:
    """Yield (type, offset, size, header_len) for boxes in [start, end)."""
    out: List[Tuple[str, int, int, int]] = []
    pos = start
    while pos + 8 <= end:
        size, raw_type = struct.unpack(">I4s", data[pos:pos + 8])
        header = 8
        if size == 1:
            if pos + 16 > end:
                break
            size = struct.unpack(">Q", data[pos + 8:pos + 16])[0]
            header = 16
        elif size == 0:
            size = end - pos
        if size < header or pos + size > end:
            break
        out.append((raw_type.decode("latin1"), pos, size, header))
        pos += size
    return out


def mp4_metadata(path: str) -> Dict[str, int]:
    """Extract duration (seconds) and pixel dimensions from moov.

    duration comes from moov/mvhd; width/height from the 16.16 fixed-point
    fields that close every moov/trak/tkhd box.
    """
    with open(path, "rb") as fh:
        data = fh.read()
    if len(data) < 8 or data[4:8] != b"ftyp":
        raise ValueError("not an ISO-BMFF/MP4 file (missing ftyp)")
    duration_sec: Optional[int] = None
    width = height = 0
    for top_type, top_pos, top_size, top_header in _mp4_boxes(data, 0, len(data)):
        if top_type != "moov":
            continue
        for mid_type, mid_pos, mid_size, mid_header in _mp4_boxes(data, top_pos + top_header, top_pos + top_size):
            if mid_type == "mvhd" and duration_sec is None:
                payload = data[mid_pos + mid_header:mid_pos + mid_size]
                version = payload[0]
                if version == 1:
                    timescale = struct.unpack(">I", payload[20:24])[0]
                    ticks = struct.unpack(">Q", payload[24:32])[0]
                else:
                    timescale = struct.unpack(">I", payload[12:16])[0]
                    ticks = struct.unpack(">I", payload[16:20])[0]
                if timescale <= 0:
                    raise ValueError("mvhd with non-positive timescale")
                duration_sec = int(round(ticks / timescale))
            elif mid_type == "trak":
                for leaf_type, leaf_pos, leaf_size, _lh in _mp4_boxes(data, mid_pos + mid_header, mid_pos + mid_size):
                    if leaf_type != "tkhd" or leaf_size < 16:
                        continue
                    tail = data[leaf_pos + leaf_size - 8:leaf_pos + leaf_size]
                    w16, h16 = struct.unpack(">II", tail)
                    if w16 >> 16 or h16 >> 16:  # first non-degenerate video track wins
                        width, height = w16 >> 16, h16 >> 16
    if duration_sec is None or duration_sec <= 0:
        raise ValueError("no usable mvhd duration")
    if width <= 0 or height <= 0:
        raise ValueError("no usable tkhd dimensions")
    return {"duration_sec": duration_sec, "width": width, "height": height}


# ------------------------------------------------------------ asset synthesis

def generate_wav(path: str, seconds: float = 6.0, rate: int = 8000) -> Dict[str, Any]:
    """Minimal legal PCM WAV: two-tone chime with fade envelope."""
    samples = int(seconds * rate)
    frames = bytearray()
    for n in range(samples):
        t = n / rate
        env = min(1.0, 4.0 * t, 4.0 * (seconds - t))
        wave = (
            0.55 * math.sin(2 * math.pi * 440.0 * t)
            + 0.30 * math.sin(2 * math.pi * 554.37 * t)
            + 0.15 * math.sin(2 * math.pi * 659.25 * t)
        )
        value = int(max(-1.0, min(1.0, wave * env)) * 32767.0)
        frames += struct.pack("<h", value)
    data = bytes(frames)
    header = b"RIFF" + struct.pack("<I", 36 + len(data)) + b"WAVE"
    header += b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16)
    header += b"data" + struct.pack("<I", len(data))
    with open(path, "wb") as fh:
        fh.write(header + data)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "audio/wav",
        "file_type": "audio",
        "extension": ".wav",
        "size": 44 + len(data),
        "duration_sec": int(seconds),
    }


def generate_midi(path: str) -> Dict[str, Any]:
    """MIDI format 0 with one track of scale notes (valid MThd/MTrk file)."""
    division = 480
    tempo_us_per_quarter = 500000  # 120 bpm
    notes = [60, 64, 67, 72, 71, 67, 64, 60]  # C major arpeggio walk

    def vlq(value: int) -> bytes:
        out = bytearray([value & 0x7F])
        value >>= 7
        while value:
            out.insert(0, 0x80 | (value & 0x7F))
            value >>= 7
        return bytes(out)

    track = bytearray()
    track += b"\x00" + bytes([0xFF, 0x51, 0x03]) + struct.pack(">I", tempo_us_per_quarter)[1:]
    for note in notes:
        track += vlq(0) + bytes([0x90, note, 96])             # note on
        track += vlq(division) + bytes([0x80, note, 0])       # note off one beat later
    track += vlq(division) + bytes([0xFF, 0x2F, 0x00])        # end of track
    header = b"MThd" + struct.pack(">IHHH", 6, 0, 1, division)
    body = b"MTrk" + struct.pack(">I", len(track)) + bytes(track)
    with open(path, "wb") as fh:
        fh.write(header + body)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "audio/midi",
        "file_type": "sheet_music",
        "extension": ".mid",
        "size": len(header) + len(body),
        "duration_sec": None,
    }


def generate_stl(path: str) -> Dict[str, Any]:
    """Hand-written binary STL: a regular tetrahedron (4 facets)."""
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    verts = [
        (-1.0, phi / 2.0, 0.0),
        (1.0, phi / 2.0, 0.0),
        (0.0, -1.0, phi / 2.0),
        (0.0, 1.0, phi / 2.0),
    ]
    faces = [(0, 1, 2), (0, 2, 3), (0, 3, 1), (1, 3, 2)]
    payload = bytearray()
    payload += b"OmniCraft demo tetrahedron (binary STL)".ljust(80, b"\0")
    payload += struct.pack("<I", len(faces))
    for a, b, c in faces:
        ax, ay, az = verts[a]
        bx, by, bz = verts[b]
        cx, cy, cz = verts[c]
        ux, uy, uz = bx - ax, by - ay, bz - az
        vx, vy, vz = cx - ax, cy - ay, cz - az
        nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
        norm = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        payload += struct.pack("<3f", nx / norm, ny / norm, nz / norm)
        for x, y, z in (verts[a], verts[b], verts[c]):
            payload += struct.pack("<3f", x, y, z)
        payload += struct.pack("<H", 0)
    with open(path, "wb") as fh:
        fh.write(bytes(payload))
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "model/stl",
        "file_type": "model3d",
        "extension": ".stl",
        "size": len(payload),
        "duration_sec": None,
    }


def generate_mod_zip(path: str) -> Dict[str, Any]:
    """Small multi-entry zip for the mod family (application/zip)."""
    entries = {
        "readme.txt": (
            "OmniCraft 演示模组包\n"
            "本包为演示验收 A5 造数生成的合法 zip 附件，用于模组下载链路与附件卡展示。\n"
        ),
        "data/notes.md": "# 演示模组说明\n\n- 纯文本演示条目 A\n- 纯文本演示条目 B\n",
        "assets/manifest.json": '{"name": "demo-mod", "version": "1.0.0", "entries": 3}\n',
    }
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, body in entries.items():
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.external_attr = 0o644 << 16
            zf.writestr(info, body)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "application/zip",
        "file_type": "mod",
        "extension": ".zip",
        "size": os.path.getsize(path),
        "duration_sec": None,
    }


_DOCX_CONTENT_TYPES = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/word/document.xml" '
    'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
    "</Types>"
)
_DOCX_RELS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" '
    'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
    'Target="word/document.xml"/>'
    "</Relationships>"
)


def generate_docx(path: str, title: str, paragraphs: List[str]) -> Dict[str, Any]:
    """Minimal OPC docx: [Content_Types].xml + _rels/.rels + word/document.xml.

    Satisfies the backend package-identity gate (document_validation.go needs
    [Content_Types].xml and word/document.xml; macro parts must be absent).
    """
    body_parts = []
    for text in [title] + paragraphs:
        escaped = (
            text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        )
        body_parts.append(
            '<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr>'
            "<w:r><w:t xml:space=\"preserve\">%s</w:t></w:r></w:p>" % escaped
        )
    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        "<w:body>%s</w:body></w:document>" % "".join(body_parts)
    )
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", _DOCX_CONTENT_TYPES)
        zf.writestr("_rels/.rels", _DOCX_RELS)
        zf.writestr("word/document.xml", document)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "file_type": "document",
        "extension": ".docx",
        "size": os.path.getsize(path),
        "duration_sec": None,
    }


def generate_csv(path: str, rows: int = 12) -> Dict[str, Any]:
    lines = ["section,item,qty,note"]
    for i in range(1, rows + 1):
        lines.append("demo-%02d,演示条目 %02d,%d,验收造数" % (i, i, i))
    body = "\n".join(lines) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "text/csv",
        "file_type": "document",
        "extension": ".csv",
        "size": len(body.encode("utf-8")),
        "duration_sec": None,
    }


def generate_text_note(path: str, body: str) -> Dict[str, Any]:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return {
        "path": path,
        "name": os.path.basename(path),
        "mime_type": "text/plain",
        "file_type": "text",
        "extension": ".txt",
        "size": len(body.encode("utf-8")),
        "duration_sec": None,
    }


def synthesize_audio(dest_dir: str, stem: str, ffmpeg_bin: Optional[str]) -> Dict[str, Any]:
    """Audio asset: ffmpeg MP3 when available, pure-Python WAV otherwise.

    Both paths must stay valid: the returned extension decides which magic
    prefix the validator expects (mirrors the backend sniffer).
    """
    if ffmpeg_bin:
        mp3_path = os.path.join(dest_dir, stem + ".mp3")
        try:
            proc = subprocess.run(
                [
                    ffmpeg_bin, "-y", "-f", "lavfi", "-i",
                    "sine=frequency=440:duration=6",
                    "-f", "lavfi", "-i", "sine=frequency=554.37:duration=6",
                    "-filter_complex", "amix=inputs=2,afade=t=in:d=0.5,afade=t=out:st=5.5:d=0.5",
                    "-codec:a", "libmp3lame", "-b:a", "128k", mp3_path,
                ],
                capture_output=True,
                text=True,
            )
        except (OSError, subprocess.SubprocessError):
            proc = None  # missing/unlaunchable binary: fall through to WAV
        if (
            proc is not None and proc.returncode == 0
            and os.path.exists(mp3_path) and os.path.getsize(mp3_path) > 0
        ):
            return {
                "path": mp3_path,
                "name": os.path.basename(mp3_path),
                "mime_type": "audio/mpeg",
                "file_type": "audio",
                "extension": ".mp3",
                "size": os.path.getsize(mp3_path),
                "duration_sec": 6,
            }
        # fall through to the WAV path on any ffmpeg failure
    return generate_wav(os.path.join(dest_dir, stem + ".wav"))


# ------------------------------------------------------------ validation

def validate_asset(asset: Dict[str, Any]) -> List[str]:
    """Offline assertions mirroring the backend upload-family gates."""
    issues: List[str] = []
    path = asset["path"]
    kind = asset["file_type"]
    ext = asset.get("extension") or os.path.splitext(path)[1].lower()
    if not os.path.exists(path):
        return ["missing file: %s" % path]
    if os.path.getsize(path) != asset["size"]:
        issues.append("size mismatch: stat=%d recorded=%d" % (os.path.getsize(path), asset["size"]))
    with open(path, "rb") as fh:
        head = fh.read(4096)
    if kind == "image":
        if head[:2] != b"\xff\xd8":
            issues.append("image missing JPEG SOI magic")
        try:
            width, height = jpeg_dimensions(path)
            if width <= 0 or height <= 0:
                issues.append("non-positive JPEG dimensions")
        except ValueError as err:
            issues.append("JPEG parse failed: %s" % err)
    elif kind == "video":
        try:
            meta = mp4_metadata(path)
            if meta["duration_sec"] > 180:
                issues.append("video duration %ds exceeds 180s budget" % meta["duration_sec"])
            if meta["width"] <= 0 or meta["height"] <= 0:
                issues.append("non-positive video dimensions")
        except ValueError as err:
            issues.append("MP4 parse failed: %s" % err)
    elif kind == "audio":
        prefixes = AUDIO_MAGIC_BY_EXT.get(ext, [])
        if not prefixes or not any(head.startswith(p) for p in prefixes):
            issues.append("audio header magic does not match extension %s" % ext)
    elif kind == "mod":
        if head[:2] != b"PK":
            issues.append("mod zip missing PK magic")
        try:
            with zipfile.ZipFile(path) as zf:
                bad = zf.testzip()
                if bad is not None:
                    issues.append("mod zip corrupt entry: %s" % bad)
                if len(zf.namelist()) < 2:
                    issues.append("mod zip too thin for archive validation")
        except zipfile.BadZipFile as err:
            issues.append("mod zip unreadable: %s" % err)
    elif kind == "model3d" and ext == ".stl":
        size = os.path.getsize(path)
        if size < 84:
            issues.append("STL smaller than fixed header")
        else:
            with open(path, "rb") as fh:
                fh.seek(80)
                count = struct.unpack("<I", fh.read(4))[0]
            if 84 + 50 * count != size:
                issues.append("STL size %d inconsistent with %d facets" % (size, count))
    elif kind == "sheet_music" and ext in (".mid", ".midi"):
        if head[:4] != b"MThd":
            issues.append("MIDI missing MThd header")
        elif len(head) < 14:
            issues.append("MIDI header truncated")
        else:
            header_len = struct.unpack(">I", head[4:8])[0]
            tracks = struct.unpack(">H", head[10:12])[0]
            if header_len != 6 or tracks < 1:
                issues.append("MIDI header fields invalid")
    elif kind == "document" and ext == ".docx":
        try:
            with zipfile.ZipFile(path) as zf:
                names = zf.namelist()
                if "[Content_Types].xml" not in names:
                    issues.append("docx missing [Content_Types].xml")
                if "word/document.xml" not in names:
                    issues.append("docx missing word/document.xml")
                if any(n.rsplit("/", 1)[-1].lower() == "vbaproject.bin" for n in names):
                    issues.append("docx carries vbaProject.bin")
                types = zf.read("[Content_Types].xml").decode("utf-8", "replace").lower()
                for marker in ("macro", "vbaProject"):
                    if marker in types:
                        issues.append("docx content types declare macro content")
        except zipfile.BadZipFile as err:
            issues.append("docx unreadable: %s" % err)
    elif kind == "document" and ext == ".csv":
        if b"\x00" in head:
            issues.append("csv contains NUL byte in head")
        else:
            printable = sum(1 for b in head if b in (0x0A, 0x0D, 0x09) or b >= 0x20)
            if head and printable / len(head) < 0.9:
                issues.append("csv printable ratio below 0.9")
    elif kind == "text":
        try:
            with open(path, "r", encoding="utf-8") as fh:
                if not fh.read().strip():
                    issues.append("text note empty")
        except UnicodeDecodeError:
            issues.append("text note not valid UTF-8")
    return issues


# ------------------------------------------------------------ library build

def ensure_demo_assets(workdir: str, use_ffmpeg: bool = True) -> Dict[str, List[Dict[str, Any]]]:
    """Materialize + validate every asset the seeding matrix needs.

    Returns a library dict: image/video sources keep absolute repo paths (no
    copies), synthesized families land in <workdir>/assets/. Re-running is
    idempotent: existing valid files are reused byte-for-byte.
    """
    assets_dir = os.path.join(workdir, "assets")
    os.makedirs(assets_dir, exist_ok=True)
    ffmpeg_bin = detect_ffmpeg() if use_ffmpeg else None

    library: Dict[str, List[Dict[str, Any]]] = {"image": [], "video": [], "audio": [], "mod": [], "sheet_music": [], "model3d": [], "document": [], "text": []}

    # -- sourced images (real JPGs, reused in place) -------------------------
    cover_names = sorted(n for n in os.listdir(COVERS_DIR) if n.lower().endswith(".jpg"))
    if len(cover_names) < 9:
        raise RuntimeError("expected >=9 real cover JPGs under %s, found %d" % (COVERS_DIR, len(cover_names)))
    for name in cover_names:
        path = os.path.join(COVERS_DIR, name)
        width, height = jpeg_dimensions(path)
        library["image"].append({
            "path": path, "name": name, "mime_type": "image/jpeg", "file_type": "image",
            "extension": ".jpg", "size": os.path.getsize(path),
            "width": width, "height": height, "duration_sec": None,
        })

    # -- sourced videos (real MP4s, reused in place) -------------------------
    for name in VIDEO_SOURCES:
        path = os.path.join(VIDEOS_DIR, name)
        meta = mp4_metadata(path)
        library["video"].append({
            "path": path, "name": name, "mime_type": "video/mp4", "file_type": "video",
            "extension": ".mp4", "size": os.path.getsize(path), "duration_sec": meta["duration_sec"],
            "width": meta["width"], "height": meta["height"],
        })
    # 3-video special needs a third real MP4: reuse fitness-1 bytes under a
    # distinct upload name (fitness-3.mp4 on disk is a mislabelled JPEG).
    extra = dict(library["video"][0])
    extra["name"] = "fitness-1-take2.mp4"
    library["video"].append(extra)

    # -- synthesized families ------------------------------------------------
    library["audio"].append(synthesize_audio(assets_dir, "demo-chime-01", ffmpeg_bin))
    library["audio"].append(synthesize_audio(assets_dir, "demo-chime-02", ffmpeg_bin))
    library["mod"].append(generate_mod_zip(os.path.join(assets_dir, "demo-mod-pack.zip")))
    library["sheet_music"].append(generate_midi(os.path.join(assets_dir, "demo-scale.mid")))
    library["model3d"].append(generate_stl(os.path.join(assets_dir, "demo-tetrahedron.stl")))
    library["document"].append(generate_docx(
        os.path.join(assets_dir, "demo-template-guide.docx"),
        "万象工坊演示模板：创作规划表",
        [
            "本 docx 由演示造数脚本以标准库构造，用于模板类文档查看器与下载链路验收。",
            "一、选题：确定主题、受众与呈现形式。",
            "二、结构：列大纲，标注每节要点与素材来源。",
            "三、排期：按周拆解任务，预留复审缓冲。",
            "四、复盘：记录数据与反馈，沉淀为下一轮模板。",
        ],
    ))
    library["document"].append(generate_csv(os.path.join(assets_dir, "demo-template-sheet.csv")))
    library["text"].append(generate_text_note(
        os.path.join(assets_dir, "demo-print-notes.txt"),
        "打印说明（演示 3D 打印随附文本）：\n"
        "材料：PLA；层高 0.2mm；填充 15%；无需支撑。\n"
        "本文件用于验收 3d_print 品类的 text 族附件展示。\n",
    ))

    # -- validate everything --------------------------------------------------
    failures: List[str] = []
    for kind, assets in library.items():
        for asset in assets:
            for issue in validate_asset(asset):
                failures.append("%s/%s: %s" % (kind, asset["name"], issue))
    if failures:
        raise RuntimeError("asset validation failed:\n  " + "\n  ".join(failures))
    return library
