package service

import (
	"context"
	"encoding/json"
	"io"
	"strings"
	"testing"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"

	"omnicraft/backend/config"
	"omnicraft/backend/internal/model"
	"omnicraft/backend/internal/pkg/llm"
)

type fakeImageGenerator struct {
	bytes    []byte
	err      error
	prompt   string
	size     string
	maxBytes int
	calls    int
}

func (f *fakeImageGenerator) GenerateImage(ctx context.Context, prompt, size string, maxImageBytes int) ([]byte, error) {
	f.calls++
	f.prompt, f.size, f.maxBytes = prompt, size, maxImageBytes
	return f.bytes, f.err
}

type fakeImageStore struct {
	put    map[string]string
	signed map[string]string
}

func newFakeImageStore() *fakeImageStore {
	return &fakeImageStore{put: map[string]string{}, signed: map[string]string{}}
}

func (f *fakeImageStore) PutAgentImage(ctx context.Context, key string, r io.Reader) error {
	raw, _ := io.ReadAll(r)
	f.put[key] = string(raw)
	return nil
}

func (f *fakeImageStore) SignedAgentImageURL(ctx context.Context, key string) (string, error) {
	return "https://cdn.omnicraft.local/signed/" + key, nil
}

func newImageTestService(t *testing.T, gen llm.AgentImageGenerator, store AgentImageStore, db *gorm.DB, limit int) *AgentService {
	t.Helper()
	cfg := &config.Config{}
	cfg.Agent.Image = config.AgentImageConfig{
		Enabled: true, Provider: "zhipu", Model: "cogview-4",
		APIBase: "https://example.invalid", APIKey: "test-key",
		SizeDefault: "1024x1024", SizeOptions: []string{"1024x1024", "1344x768"},
		MaxImageBytes: 1024 * 1024, TimeoutSec: 5, SessionImageLimit: limit,
		PricePerImageCNY: 0.06,
	}
	s := &AgentService{cfg: cfg, db: db}
	s.SetImageTool(cfg.Agent.Image, gen, store)
	return s
}

func TestGenerateImageToolUnavailableByConfig(t *testing.T) {
	cfg := &config.Config{}
	cfg.Agent.Image = config.AgentImageConfig{Enabled: false}
	s := &AgentService{cfg: cfg}
	if s.imageToolAvailable() {
		t.Fatal("disabled image config must keep the tool unavailable")
	}
	for _, def := range s.ToolDefinitions() {
		if def.Name == ToolGenerateImage {
			t.Fatal("generate_image must not be advertised when unconfigured")
		}
	}
	// enabled switch but no key: still unavailable (fail-closed)
	cfg.Agent.Image.Enabled = true
	if s.imageToolAvailable() {
		t.Fatal("missing API key must keep the tool unavailable")
	}
}

func TestGenerateImageToolContract(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatal(err)
	}
	if err := db.AutoMigrate(&model.AgentMessage{}, &model.AgentConversation{}); err != nil {
		t.Fatal(err)
	}
	gen := &fakeImageGenerator{bytes: []byte("png-bytes")}
	store := newFakeImageStore()
	s := newImageTestService(t, gen, store, db, 2)

	// advertised once configured
	found := false
	for _, def := range s.ToolDefinitions() {
		if def.Name == ToolGenerateImage {
			found = true
		}
	}
	if !found {
		t.Fatal("configured image tool must be advertised")
	}

	// invalid args: empty prompt
	if _, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"  "}`), 1, 10, 0, nil); err != ErrAgentToolInvalidArgs {
		t.Fatalf("empty prompt err = %v", err)
	}
	// invalid args: oversized prompt
	if _, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"`+strings.Repeat("长", 201)+`"}`), 1, 10, 0, nil); err != ErrAgentToolInvalidArgs {
		t.Fatalf("oversized prompt err = %v", err)
	}
	// unknown fields rejected (strict decode)
	if _, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"x","evil":1}`), 1, 10, 0, nil); err != ErrAgentToolInvalidArgs {
		t.Fatalf("unknown field err = %v", err)
	}

	// success: unknown size falls back to default; provider URL never surfaces
	outcome, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"水彩风格的灯塔","size":"bogus"}`), 1, 10, 0, nil)
	if err != nil {
		t.Fatal(err)
	}
	if outcome.Image == nil || outcome.Image.URL == "" || outcome.Image.OSSKey == "" {
		t.Fatalf("image outcome incomplete: %+v", outcome.Image)
	}
	if !strings.HasPrefix(outcome.Image.OSSKey, "agent-images/10/") {
		t.Fatalf("object key must live under agent-images/<conversation>/: %s", outcome.Image.OSSKey)
	}
	if !strings.Contains(outcome.Image.URL, "cdn.omnicraft.local") {
		t.Fatalf("URL must be the platform-signed one: %s", outcome.Image.URL)
	}
	if gen.size != "1024x1024" {
		t.Fatalf("unknown size must fall back to default, got %s", gen.size)
	}
	if got := store.put[outcome.Image.OSSKey]; got != "png-bytes" {
		t.Fatalf("store must hold the generated bytes, got %q", got)
	}
	if outcome.Image.CostCNY != 0.06 {
		t.Fatalf("cost estimate = %v", outcome.Image.CostCNY)
	}

	// second image OK (limit 2), third hits the quota degradation path
	if _, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"第二张"}`), 1, 10, 1, nil); err != nil {
		t.Fatal(err)
	}
	_, err = s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"第三张"}`), 1, 10, 2, nil)
	if err != ErrAgentImageQuotaExceeded {
		t.Fatalf("third call err = %v, want quota exceeded", err)
	}
	if gen.calls != 2 {
		t.Fatalf("quota must stop provider calls, made %d", gen.calls)
	}
}

func TestGenerateImageQuotaCountsPersistedSteps(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatal(err)
	}
	if err := db.AutoMigrate(&model.AgentMessage{}, &model.AgentConversation{}); err != nil {
		t.Fatal(err)
	}
	// two persisted generate_image steps from earlier turns
	for i := 0; i < 2; i++ {
		if err := db.Create(&model.AgentMessage{
			ConversationID: 42, Role: "assistant",
			ToolCalls: model.JSONMap{"phase": "tools", "steps": []any{
				map[string]any{"name": ToolGenerateImage, "status": "success"},
				map[string]any{"name": ToolSearchContent, "status": "success"},
			}},
		}).Error; err != nil {
			t.Fatal(err)
		}
	}
	gen := &fakeImageGenerator{bytes: []byte("x")}
	s := newImageTestService(t, gen, newFakeImageStore(), db, 2)

	_, err = s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"再来一张"}`), 1, 42, 0, nil)
	if err != ErrAgentImageQuotaExceeded {
		t.Fatalf("persisted steps must count toward the budget: err = %v", err)
	}
}

func TestGenerateImageProviderFailure(t *testing.T) {
	gen := &fakeImageGenerator{err: context.DeadlineExceeded}
	s := newImageTestService(t, gen, newFakeImageStore(), nil, 5)
	_, err := s.ExecuteToolInConversation(context.Background(), ToolGenerateImage,
		json.RawMessage(`{"prompt":"超时场景"}`), 1, 10, 0, nil)
	if err == nil || !strings.Contains(err.Error(), "image generation") {
		t.Fatalf("provider failure must surface, got %v", err)
	}
}
